kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: amq-broker-init-rhel8
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 7.11.6
      from:
        kind: DockerImage
        name: 'registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.6'
      generation: 1
      importPolicy: {}
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: amq-init
  labels:
    app: amq-auth-init
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  lookupPolicy:
    local: false
