apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: rhsso-security
spec:
  loginModules:
    keycloakLoginModules:
      - configuration:
          authServerUrl: 'https://keycloak-artemis-keycloak-example.apps.asouza01.lab.upshift.rdu2.redhat.com/auth'
          verifyTokenAudience: true
          confidentialPort: 0
          sslRequired: all
          resource: amq-broker
          principalAttribute: preferred_username
          realm: amq-broker-realm
          useResourceRoleMappings: true
          enableBasicAuth: true
          credentials:
            - key: secret
              value: amq-broker-secret-value
        moduleType: directAccess
        name: login-rhsso-broker-module
      - configuration:
          authServerUrl: 'https://keycloak-artemis-keycloak-example.apps.asouza01.lab.upshift.rdu2.redhat.com/auth'
          verifyTokenAudience: false
          confidentialPort: 0
          sslRequired: all
          resource: amq-console
          principalAttribute: preferred_username
          realm: amq-broker-realm
          useResourceRoleMappings: true
          enableBasicAuth: true
          publicClient: true
        moduleType: bearerToken
        name: login-keycloak-console-module
    propertiesLoginModules:
      - name: prop-module
        users:
          - name: "sam"
            password: "samspassword"
            roles:
              - "admin"
  securityDomains:
    brokerDomain:
      loginModules:
        - debug: true
          flag: required
          name: login-rhsso-broker-module
      name: activemq
    consoleDomain:
      loginModules:
        - debug: true
          flag: sufficient
          name: login-keycloak-console-module
        - debug: true
          flag: required
          name: prop-module
      name: console
  securitySettings:
    broker:
      - match: '#'
        permissions:
          - operationType: createAddress
            roles:
              - admin
              - consumer
              - producer
          - operationType: deleteAddress
            roles:
              - admin
          - operationType: createDurableQueue
            roles:
              - admin
              - consumer
              - producer
          - operationType: deleteDurableQueue
            roles:
              - admin
          - operationType: createNonDurableQueue
            roles:
              - admin
              - consumer
              - producer
          - operationType: deleteNonDurableQueue
            roles:
              - admin
          - operationType: send
            roles:
              - admin
              - consumer
              - producer
          - operationType: consume
            roles:
              - admin
              - consumer
              - producer
          - operationType: browse
            roles:
              - admin
              - consumer
              - producer
      - match: activemq.management.#
        permissions:
          - operationType: createNonDurableQueue
            roles:
              - admin
          - operationType: createAddress
            roles:
              - admin
          - operationType: consume
            roles:
              - admin
          - operationType: manage
            roles:
              - admin
          - operationType: send
            roles:
              - admin
    management:
      authorisation:
        allowedList:
          - domain: hawtio
        roleAccess:
          - accessList:
              - method: list*
                roles:
                  - admin
                  - viewer
              - method: get*
                roles:
                  - admin
                  - viewer
              - method: is*
                roles:
                  - admin
                  - viewer
              - method: set*
                roles:
                  - admin
              - method: browse*
                roles:
                  - admin
              - method: count*
                roles:
                  - admin
              - method: '*'
                roles:
                  - admin
            domain: org.apache.activemq.artemis
    hawtioRoles:
        - admin
        - viewer

